packages:
  - packages/*
  - docs
  - slidev
catalog:
  "@antfu/eslint-config": ^2.27.3
  "@commander-js/extra-typings": ^12.0.1
  "@rollup/plugin-alias": ^5.1.0
  "@rollup/plugin-commonjs": ^25.0.8
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^15.2.3
  "@rollup/pluginutils": ^5.1.0
  "@slidev/cli": ^0.49.24
  "@slidev/theme-default": ^0.25.0
  "@types/fs-extra": ^11.0.4
  "@types/inquirer": ^9.0.7
  "@types/node": ^20.16.5
  "@unocss/eslint-plugin": 0.59.0-beta.1
  adm-zip: ^0.5.12
  bumpp: ^9.8.1
  cac: ^6.7.14
  chalk: ^5.3.0
  commander: ^12.0.0
  consola: ^3.2.3
  crypto-js: ^4.2.0
  download-git-repo: ^3.0.2
  esbuild: ^0.23.1
  eslint: ^9.10.0
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  gray-matter: ^4.0.3
  js-yaml: ^4.1.0
  md5: ^2.3.0
  ofetch: ^1.4.1
  ora: ^8.0.1
  prompts: ^2.4.2
  rimraf: ^6.0.1
  rollup: ^4.21.2
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-typescript2: ^0.36.0
  rollup-plugin-visualizer: ^5.12.0
  simple-git: ^3.27.0
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tslib: ^2.7.0
  tsup: ^8.2.4
  tsx: ^4.19.0
  typescript: ^5.5.4
  unplugin-auto-import: ^0.18.2
  unplugin-detect-duplicated-deps: ^2.0.0
  unplugin-externalize-deps: ^0.0.10
  vite: ^5.4.3
  vite-plugin-node-polyfills: ^0.21.0
  vue: ^3.4.33
  vue-demi: ^0.14.8
  yaml: ^2.6.0
