packages:
  - packages/*
  - docs
  - slidev

catalog:
  typescript: ^5.9.3

catalogs:
  build:
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^25.0.8
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-node-resolve': ^15.3.1
    '@rollup/pluginutils': ^5.3.0
    esbuild: ^0.23.1
    rollup: ^4.59.0
    rollup-plugin-dts: ^6.3.0
    rollup-plugin-esbuild: ^6.2.1
    rollup-plugin-typescript2: ^0.36.0
    rollup-plugin-visualizer: ^5.14.0
    unplugin-auto-import: ^0.18.6
    unplugin-detect-duplicated-deps: ^2.0.0
    unplugin-externalize-deps: ^0.0.10
    vite: ^5.4.21
    vite-plugin-node-polyfills: ^0.21.0
  catalog_tool:
    '@codemod.com/cli-darwin-arm64': ^1.3.3
    codemod: ^1.5.0
  cli:
    '@commander-js/extra-typings': ^12.0.1
    cac: ^6.7.14
    chalk: ^5.3.0
    commander: ^12.0.0
    consola: ^3.4.2
    ora: ^8.0.1
    prompts: ^2.4.2
  frontend:
    vue: ^3.4.33
    vue-demi: ^0.14.8
  lint:
    '@antfu/eslint-config': ^2.27.3
    '@unocss/eslint-plugin': 0.59.0-beta.1
    eslint: ^9.39.3
  ppt:
    '@slidev/cli': ^0.49.24
    '@slidev/theme-default': ^0.25.0
    vitepress: ^1.6.4
  script:
    bumpp: ^9.11.1
    rimraf: ^6.1.3
    tsx: ^4.21.0
  test:
    vitest: ^4.0.18
  tool:
    adm-zip: ^0.5.12
    crypto-js: ^4.2.0
    download-git-repo: ^3.0.2
    fast-glob: ^3.3.3
    fs-extra: ^11.3.3
    simple-git: ^3.32.2
    yaml: ^2.8.2
  types:
    '@types/fs-extra': ^11.0.4
    '@types/inquirer': ^9.0.7
    '@types/node': ^20.19.33
    '@types/prompts': ^2.4.9
