/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const GitFetchType: typeof import('./types/global')['GitFetchType']
  const GitHttpOption: typeof import('./types/global')['GitHttpOption']
  const a: typeof import('./types/global')['a']
}
